-- !Ups
ALTER TABLE account ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE airport ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE boarding_pass ALTER COLUMN boarding_time TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE boarding_pass ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE booking ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE booking_leg ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE flight ALTER COLUMN scheduled_departure TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE flight ALTER COLUMN scheduled_arrival TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE flight ALTER COLUMN actual_departure TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE flight ALTER COLUMN actual_arrival TYPE TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE flight ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE frequent_flyer ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE passenger ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE phone ALTER COLUMN update_ts TYPE TIMESTAMP WITHOUT TIME ZONE;



-- !Downs
ALTER TABLE account ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE airport ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE boarding_pass ALTER COLUMN boarding_time TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE boarding_pass ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE booking ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE booking_leg ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE flight ALTER COLUMN scheduled_departure TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE flight ALTER COLUMN scheduled_arrival TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE flight ALTER COLUMN actual_departure TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE flight ALTER COLUMN actual_arrival TYPE TIMESTAMP WITH TIME ZONE;
ALTER TABLE flight ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE frequent_flyer ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE passenger ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;

ALTER TABLE phone ALTER COLUMN update_ts TYPE TIMESTAMP WITH TIME ZONE;
